version: "3.7"
services:
  redpanda-1.local:
    container_name: redpanda-1.local
    image: docker.vectorized.io/vectorized/redpanda:latest
#    environment:
#      RP_BOOTSTRAP_USER: "admin:adminpassword"
    command:
    - redpanda start
    - --smp 1
    - --overprovisioned
    - --memory 1G
    volumes:
    - ./redpanda-config/redpanda-1:/etc/redpanda
    - ./certs:/etc/redpanda/certs
    - ./redpanda-data/redpanda-1:/var/lib/redpanda/data
    ports:
    - 9192:9192
    - 9744:9744
    - 8181:8181
    - 8182:8182

