rpk:
  kafka_api:
    brokers:
    - localhost:9092
#    tls:
#      cert_file: <current-dir>/certs/node.crt
#      key_file: <current-dir>/certs/node.key
#      truststore_file: <current-dir>/certs/ca.crt
  admin_api:
    addresses:
    - localhost:9644
#    tls:
#      cert_file: <current-dir>/certs/node.crt
#      key_file: <current-dir>/certs/node.key
#      truststore_file: <current-dir>/certs/ca.crt

